import localFont from 'next/font/local'
import "./globals.css";
import { NavbarLayout } from './components/Navbar';
import { FooterLayout } from './components/Footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const unna = localFont({
  src: '././fonts/JosefinSans-VariableFont_wght.ttf',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unna.className} antialiased min-h-screen h-full flex flex-col`}
      >
        <NavbarLayout/>
        <main className='flex-1'>
          {children}
        </main>
        
        <FooterLayout/>
      </body>
    </html>
  );
}
